name: Sync Data from GSheet

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Download CSV from GSheet 2026
        run: |
          curl -L "https://docs.google.com/spreadsheets/d/e/2PACX-1vQyI8mksdqrv4RF0OBH_Hi2BdZ17fYNBU2_scPnUFb0EkI8QFFRwTEpJtoQvKoXJQaWUoGC7bOhGtB1/pub?output=csv" -o data_2026.csv
      
      - name: Download CSV from GSheet 2025
        run: |
          curl -L "https://docs.google.com/spreadsheets/d/e/2PACX-1vSfY4FSedZDglBnuz8UWZXdhg9LJGDKcAjGEYENyL8rTXAqguTTqZL0IQfwhC0KGFh_8POa0oqM8KMf/pub?output=csv" -o data_2025.csv
      
      - name: Convert CSV to JSON using npx
        run: |
          npx csvtojson data_2026.csv > data_2026.json
          npx csvtojson data_2025.csv > data_2025.json
      
      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data_2026.json data_2025.csv data_2025.json
          git commit -m "Auto update data from GSheet [skip ci]" || echo "No changes"
          git push
